In [2]:
import pandas as pd

datos = {
    'SalesOrderID': [43659, 43660, 43661, 43662, 43663],
    'Status': [5, 5, 5, 6, 5],
    'TotalDue': [20565.18, 1294.25, 32726.47, 500.00, 714.70]
}

df = pd.DataFrame(datos)

df

   SalesOrderID  Status  TotalDue
0         43659       5  20565.18
1         43660       5   1294.25
2         43661       5  32726.47
3         43662       6    500.00
4         43663       5    714.70

In [3]:
df[df['TotalDue'] > 1000]

   SalesOrderID  Status  TotalDue
0         43659       5  20565.18
1         43660       5   1294.25
2         43661       5  32726.47

In [4]:
df[(df['Status'] == 5) & (df['TotalDue'] > 1000)]

   SalesOrderID  Status  TotalDue
0         43659       5  20565.18
1         43660       5   1294.25
2         43661       5  32726.47

In [5]:
df.sort_values(by='TotalDue', ascending=False)

   SalesOrderID  Status  TotalDue
2         43661       5  32726.47
0         43659       5  20565.18
1         43660       5   1294.25
4         43663       5    714.70
3         43662       6    500.00

In [6]:
df[(df['Status'] == 5) & (df['TotalDue'] > 1000)].sort_values(by='TotalDue',ascending=False).head(2)

   SalesOrderID  Status  TotalDue
2         43661       5  32726.47
0         43659       5  20565.18

In [7]:
datos = {
    'SalesOrderID': [43659, 43660, 43661, 43662, 43663, 43664],
    'CustomerID': [11000, 11000, 11001, 11001, 11000, 11002],
    'Status': [5, 5, 5, 5, 5, 5],
    'TotalDue': [2000, 1500, 3000, 4000, 500, 1200]
}

df = pd.DataFrame(datos)
df

   SalesOrderID  CustomerID  Status  TotalDue
0         43659       11000       5      2000
1         43660       11000       5      1500
2         43661       11001       5      3000
3         43662       11001       5      4000
4         43663       11000       5       500
5         43664       11002       5      1200

In [8]:
df.groupby('CustomerID')['TotalDue'].sum().reset_index()

   CustomerID  TotalDue
0       11000      4000
1       11001      7000
2       11002      1200

In [9]:
df.groupby('CustomerID').agg(
    MontoTotal=('TotalDue', 'sum'),
    TotalOrdenes=('SalesOrderID', 'count'),MontoPromedio=('TotalDue',lambda x: round(x.mean(),2))
).reset_index()

   CustomerID  MontoTotal  TotalOrdenes  MontoPromedio
0       11000        4000             3        1333.33
1       11001        7000             2        3500.00
2       11002        1200             1        1200.00

In [10]:
df_resumen = df.groupby('CustomerID').agg(
    MontoTotal=('TotalDue', 'sum'),
    TotalOrdenes=('SalesOrderID', 'count')
).reset_index()

datos_clientes = {
    'CustomerID': [11000, 11001, 11002],
    'NombreCliente': ['Jon Yang', 'Eugene Huang', 'Ruben Torres']
}
df_clientes = pd.DataFrame(datos_clientes)

In [11]:
df_final = pd.merge(df_resumen, df_clientes, on='CustomerID', how='inner')
df_final

   CustomerID  MontoTotal  TotalOrdenes NombreCliente
0       11000        4000             3      Jon Yang
1       11001        7000             2  Eugene Huang
2       11002        1200             1  Ruben Torres